# JumpPad Plugin Konfiguration

# JumpPad Einstellungen
jumppad:
  # Standard Block für JumpPads (kann pro Region überschrieben werden)
  default-block: SLIME_BLOCK

  # Standard Sprung Stärke (vertikal) (kann pro Region überschrieben werden)
  default-strength: 1.5

  # Standard Vorwärts Stärke (horizontal) (kann pro Region überschrieben werden)
  # 0.0 = kein Vorwärtsschub, nur vertikaler Sprung
  # Höhere Werte = stärkerer Schub in Blickrichtung
  default-forward-strength: 0.8

  # Standard Sound (kann pro Region überschrieben werden)
  default-sound: ENTITY_SLIME_SQUISH

# Nachrichten Einstellungen
messages:
  # Nachrichten aktivieren/deaktivieren
  enabled: true

  # Nachricht beim Springen (MiniMessage Format)
  jump: "<green>Du wurdest von einem JumpPad katapultiert!"

  # Admin Nachrichten
  region-created: "<green>Region '<region>' wurde erfolgreich erstellt!"
  region-deleted: "<red>Region '<region>' wurde gelöscht!"
  no-permission: "<red>Du hast keine Berechtigung für diesen Befehl!"
  region-not-found: "<red>Region '<region>' wurde nicht gefunden!"